# file: api.yml
---
- hosts: api
  sudo: true
  user: vagrant
  gather_facts: no
  remote_user: root
  vars:
    app:
      user: vagrant
    git:
      repos_url: git@github.com:Twinuma/oreno-provisioning.git
      repos_dir: /home/vagrant/test
      branch: master
    doc_root: test
    domain: api.test.me
  vars_files:
    - roles/mysql/vars/mysql.yml
  roles:
    - init
    - httpd
    - app
    - php56
    - mysql
    - composer
